version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ${DOCKGE_STACKS_DIR}:${DOCKGE_STACKS_DIR}
    env_file:
      - ../.env.shared
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=${DOCKGE_STACKS_DIR}
    networks:
      - caddy
      - default
networks:
  caddy:
    external: true
